### ISSUE TITLE
GameFeatureData binds InputContext to Controller not Pawn

### ISSUE THREAD

**Issue by germantraut** [lucoiso/UEModularFeatures_ExtraActions#13]
The Controller should only be the "high level input" Abilities should always bind to the pawn instead. Easy example would be: Possess a vehicle pawn. If the Input binding is at Controller level they will stick to it and we have to remove them and apply the new ones. 

The plugin has a dropdown to bind the input to the pawn, but this does not work. The bindings are always to the controller.
![image](https://user-images.githubusercontent.com/28385193/200336193-d3ca6782-8804-40be-8023-4cd7cdcea5ea.png)

**Comment by lucoiso** [comment]
Hi! @germantraut  : )

Thanks for contacting!

I pushed the commit to the [v1.2.0](https://github.com/lucoiso/UEModularFeatures_ExtraActions/tree/v1.2.0) branch and also created a new branch in the example repository: https://github.com/lucoiso/MFA_ExampleProject/tree/v1.2.0

Now in this example, abilities are bound to the controller and movement to the character to test and show the binding on different owners

_Note: The controller in this example is only responsible for sending InputID notifications when the input is pressed or released._

## Issue

The input component on pawns were returning null, fixed by setting the plugin to get the input component from the controller independently of the binding owner.
